#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'tb3-move','console_scripts','tbp'
__requires__ = 'tb3-move'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('tb3-move', 'console_scripts', 'tbp')()
    )
