#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'ar-track','console_scripts','stop_tb3'
__requires__ = 'ar-track'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('ar-track', 'console_scripts', 'stop_tb3')()
    )
