#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'move-turtle-pkg','console_scripts','ss'
__requires__ = 'move-turtle-pkg'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('move-turtle-pkg', 'console_scripts', 'ss')()
    )
